version: '3'

services:
  reseda:
    image: registry.digitalocean.com/reseda-contained/reseda-rust 
    container_name: reseda-rust
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 8443:8443/udp
      - 80:80
      - 443:443
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always