version: '3.7'

services:
  wireguard:
    image: docker.io/unrealgdev/reseda-rust 
    container_name: reseda-rust
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - SERVERPORT=51820
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      -  ./configs/:/configs
      - /lib/modules:/lib/modules
    ports:
      # Wireguard
      - 51820:51820/udp
      # Reseda Websockets
      - 80:80
      - 443:443
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped