apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: reseda
  name: reseda
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: reseda
    spec:
      containers:
        image: docker.io/unrealgdev/reseda-rust
        name: reseda-rust
        ports:
        - containerPort: 8443
          protocol: UDP
        - containerPort: 80
        - containerPort: 443
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
      restartPolicy: Always
status: {}
