name: Build Docker image and Push to DOCR.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Build the Docker image
      run: docker build . -t unrealgdev/reseda-rust:latest --build-arg db=${{ secrets.DATABASE_URL }} --build-arg mesh_auth=${{ secrets.MESH_AUTH_KEY }} --build-arg access_key=${{ secrets.ACCESS_KEY }}
    -
      name: Push the Docker image
      run: docker push unrealgdev/reseda-rust:latest
